name    'counsyl-windows'
version '0.9.2'
source  'git://github.com/counsyl/puppet-windows.git'
author  'Counsyl, Inc.'
license 'Apache License, Version 2.0'
summary 'Collection of useful Puppet manifests for Windows-based platforms.'
description 'Collection of useful Puppet manifests for Windows-based platforms.'
project_page 'https://github.com/counsyl/puppet-windows'

dependency 'counsyl/sys', '>= 0.9.14'
dependency 'joshcooper/powershell', '>= 0.0.6'
dependency 'puppetlabs/registry', '>= 1.0.0'
